# Generated by Django 4.1.2 on 2023-02-28 08:12

from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "year",
                    models.CharField(default=players.models.get_year, max_length=30),
                ),
                ("teams", models.ManyToManyField(to="players.team")),
            ],
        ),
    ]
