# Generated by Django 4.1.2 on 2023-02-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0005_sponsor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.sponsor",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="players.team"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sponsor",
            name="team",
            field=models.ManyToManyField(
                related_name="sponsor", through="players.Sponsorship", to="players.team"
            ),
        ),
    ]
